title:              La Force du Marketing de Partenariat Dans Votre Stratégie Marketing Pour Développer Votre Business
email:              hello@matchmalo.com
description:        Des conseils pratiques en matière de marketing et des guides de collaboration entre marques B2B qui vous aideront à développer votre entreprise avec un budget réduit.
author:             Ulrich Medenou
baseurl:            ""
url:                "https://blog.matchmalo.com"

# Social Profiles
twitter_username: matchmalo
github_username:    
facebook_username:  groups/b2bpartnershipmarketing 
instagram_username:  b2b_collaboration
linkedin_username: company/matchmalo

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           6
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
